import type { NextPage } from "next";
import Head from "next/head";
import {
  Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
  Box,
  Heading,
  Button,
} from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>My Finances</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        display="flex"
        flexDirection="row"
        w="80vw"
        justifyContent="space-between"
      >
        <Heading>Total R$ 999.99</Heading>
        <Button
          bg="green.400"
          color="white"
          _hover={{ bg: "green.300" }}
          _active={{ bg: "green.500" }}
        >
          Adicionar Dispesa
        </Button>
      </Box>
      <Box
        mt={5}
        border="1px solid"
        borderColor="gray.100"
        borderWidth={2}
        borderRadius="md"
        w={"80vw"}
      >
        <TableContainer>
          <Table variant="simple">
            <Thead>
              <Tr>
                <Th isNumeric>ID</Th>
                <Th>DATA</Th>
                <Th>Descrição</Th>
                <Th>Categoria</Th>
                <Th>Valor</Th>
              </Tr>
            </Thead>
            <Tbody>
              <Tr>
                <Th isNumeric>1234</Th>
                <Th>13/07/2022</Th>
                <Th>VandalHearts</Th>
                <Th>Game</Th>
                <Th>R$ 59,90</Th>
              </Tr>
            </Tbody>
          </Table>
        </TableContainer>
      </Box>
    </>
  );
};

export default Home;
