import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import {
  Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
  Box,
  Heading,
  Button,
} from "@chakra-ui/react";
import { useEffect, useState } from "react";
import { api } from "../services/api";

interface IExpenses{
  id: number;
  date: number;
  description: string;
  category: string;
  value: number
}

const Home: NextPage = () => {
  const [expenses, setExpenses] = useState<IExpenses[]>([]);

  useEffect(() => {
    api.get("/expenses").then((resp) => setExpenses(resp.data));
  }, []);

  const toBRL = (value: number) => {
    return value.toLocaleString('pt-BR' , {
      currency: 'BRL',
      style: 'currency',
    })
  }

  return (
    <>
      <Head>
        <title>My Finances</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Box
        w="100vw"
        display="flex"
        flexDirection="row"
        justifyContent="space-between"
      >
        <Heading>Total R$ 999.99</Heading>
        <Button
          bg="green.400"
          color="white"
          _hover={{ bg: "green.300" }}
          _active={{ bg: "green.500" }}
        >
          Adicionar Dispesa
        </Button>
      </Box>
      <Box
        mt={5}
        border="1px solid"
        borderColor="gray.100"
        borderWidth={2}
        borderRadius="md"
        w="100vw"
      >
        <TableContainer>
          <Table variant="simple">
            <Thead>
              <Tr>
                <Th isNumeric>ID</Th>
                <Th>DATA</Th>
                <Th>Descrição</Th>
                <Th>Categoria</Th>
                <Th>Valor</Th>
              </Tr>
            </Thead>
            <Tbody>
              {expenses.map((expense, index) => (
                <Tr key={index}>
                  <Th isNumeric>{expense.id}</Th>
                  <Th>{new Date(expense.date).toLocaleDateString('pt-BR')}</Th>
                  <Th>{expense.description}</Th>
                  <Th>{expense.category}</Th>
                  <Th>{toBRL(expense.value)}</Th>
                </Tr>
              ))}
            </Tbody>
          </Table>
        </TableContainer>
      </Box>
      </main>
    </>
  );
};

export default Home;
